### ISSUE TITLE
Weekend 1 / ABot Speaker Crash.

### ISSUE THREAD

**Issue by SantiagoCalebe** [SadeceNicat/Hybrid-Engine#3]
When you enter ANY SONG OF WEEKEND 1, it doesn't mean what difficulty, it gives this error:  

states/stages/objects/ABotSpeaker.hx (line 56)
states/stages/PhillyStreets.hx (line 134) backend/BaseStage.hx (line 61) 
states/stages/PhillyStreets.hx (line 25) 
states/PlayState.hx (line 405) 
flixel/FlxGame.hx (line 639) 
flixel/FlxGame.hx (line 726) 
flixel/FlxGame.hx (line 679) 
flixel/FlxGame.hx (line 558) 
openfl/events/EventDispatcher.hx (line 426) 
openfl/display/DisplayObject.hx (line 1398)  

Uncaught Error: Null Object Reference.

Reading you can see that it's a problem with ABot.

___________________________________________________________________________________

I am in 64 bits version downloaded from GB.

**Comment by SadeceNicat** [comment]
I'm currently struggling with this issue but there is a workaround. Go to weekend1 from the story menu and exit and enter freeplay. It works.

**Comment by SantiagoCalebe** [comment]
Instead of` viz.animation.curAnim.finish();`, you could use `viz.animation.curAnim.restart();`

**Comment by SadeceNicat** [comment]
I fixed the problem. It was related to stickers. The error has been resolved in the new version.
